### PR TITLE
Changes to Chapter 2

### PR DESCRIPTION
**Pull request by kobyflo**
Some design editing, also language improvements and simpler explanations. 
I did not change the explanation for finding the Environment -tab because it is more consitient with what people are used from their internet browsers and excel. I figured it is explained in the text even. If there are >2 missunderstanding complaints, we can try to find a more intuitive explanation ;)

### CODE REVIEW

**Comment by JoseAlanis** [comment]
Thanks @kobyflo; I'll check it out later

**Comment by JoseAlanis** [comment]
I updated your PR by resolving some merge conflicts. Thanks for the additions!

**Comment by JoseAlanis** [comment]
I updated your PR by resolving some merge conflicts. Thanks for the additions!

**Comment by kobyflo** [comment]
Thank you! Where can I see the latest version of chapter 02? I want to make sure the improvements I`ve done made it into the book. I figure every time I delete some text or reorder a list it produces a conflict that needs to be resolved by you, sorry for that.

**Comment by JoseAlanis** [comment]
> Thank you! Where can I see the latest version of chapter 02? I want to make sure the improvements I`ve done made it into the book. I figure every time I delete some text or reorder a list it produces a conflict that needs to be resolved by you, sorry for that.

https://amd-lab.github.io/R-Kurs-Buch/

**Pull request merged**
